### ISSUE TITLE
Missing views

### ISSUE THREAD

**Issue by bbelderbos** [JAWD-001/peer_mentoring#17]
I see we have these models:

```
$ agg models.Mode
account_management/models.py
11:class Interest(models.Model):
20:class Photo(models.Model):
30:class UserProfile(models.Model):

groups/models.py
10:class Avatar(models.Model):
19:class Category(models.Model):
27:class Group(models.Model):
39:class Post(models.Model):
56:class Comment(models.Model):
```

Can you list out here which ones will be managed in the admin vs in the front-end, that is for which ones we still need views? Then we can work on them in individual issues. Thanks.

**Comment by JAWD-001** [comment]
I was going to have them be user managed. Therefore I will need some views. Is there a way to include a form within another form? As in can a user create a category or avatar at the same time they are making the group? I wanted to be able to reuse categories during group creation, that's why I wanted to have categories be more dynamic.

**Comment by JAWD-001** [comment]
Groups joined and groups managed should be added views, can get to those tonight/tomorrow with some help.

**Comment by bbelderbos** [comment]
ok let's look at this, again I don't see new PRs? please use branches + open PR for every chunk of work so I can review, thanks, refresher if needed:

    - Project Git Workflow - https://pybites.mykajabi.com/products/pybites-developer-mindset/categories/2560320/posts/9297325

**Comment by bbelderbos** [comment]
Getting close here, what views still need to get done?
