### ISSUE TITLE
Make a link from group to chat

### ISSUE THREAD

**Issue by bbelderbos** [JAWD-001/peer_mentoring#18]
When I go to http://localhost:8000/chat/ I see we have this route `chat/ room/<int:group_id>/ [name='group_chat_room']`, on the group detail we need a button / link to link to a group's room (or rooms? Will there be 1 or many chat rooms per group?)

**Comment by JAWD-001** [comment]
One room per group, should we increase the capacity of requests on the channels-redis layer? If I remember correctly, the docs mentioned that 100 requests were the standard.

**Comment by JAWD-001** [comment]
Also, starting to think that group members should be the manytomany and not groups_joined (on the userprofile model), what do you think?

**Comment by JAWD-001** [comment]
Added some stuff for joining and leaving groups, haven't tested yet because I would like for you to look at it and tell me what you think. Can we use buttons for the views instead of taking us to a whole new page? Kind of like how more modern websites do it or should we just have a separate template for each?

**Comment by JAWD-001** [comment]
Added some stuff for joining and leaving groups, haven't tested yet because I would like for you to look at it and tell me what you think. Can we use buttons for the views instead of taking us to a whole new page? Kind of like how more modern websites do it or should we just have a separate template for each?

**Comment by bbelderbos** [comment]
> One room per group, should we increase the capacity of requests on the channels-redis layer? If I remember correctly, the docs mentioned that 100 requests were the standard.

I would not worry about this yet at this point.

**Comment by bbelderbos** [comment]
> Added some stuff for joining and leaving groups, haven't tested yet because I would like for you to look at it and tell me what you think. Can we use buttons for the views instead of taking us to a whole new page? Kind of like how more modern websites do it or should we just have a separate template for each?

I don't see a new PR? Can you submit your code please? I looked here https://github.com/JAWD-001/peer_mentoring/commits/main but the separate commits don't seem related to this ... thanks.

**Comment by JAWD-001** [comment]
Yeah, I'll look it up for tomorrow.

**Comment by JAWD-001** [comment]
This is done
